config/routes.rb
  Rails.application.routes.draw do
    root"departments#index"
      resources :departments
    
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/department.rb
class Department < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base


    # class ApplicationController < ActionController::Base
    #     before_action :verify_paid
      
    #     def verify_paid
    #       @paid = true
    #     end
    #   end


end

app/controllers/departments_controller.rb
class DepartmentsController < ApplicationController
  before_action :set_sub, only: [:show, :update, :edit, :destroy]

  def index
    @departments = Department.all
      end

  def show
    @departments = Department.all
  end

  def new
    @department = departments.new
    render partial: "form"
  end

  def edit
    #GET 
    render partial: "form"
  
  end



  def create
    @department = Department.new(department_params)
    
    if @departmnet.save
      redirect_to departments_path
    else
      render :new
    end
  end

  
 
  private
 
    def pages_params
      params.require(:page).permit(:title, :author, :body)
    end

  def update
    if @department.update(department_params)
      redirect_to @department
    else
      render :edit
    end
  end

  def destroy
    @department.destroy
    redirect_to departments_path
  end

  private
    
    def set_sub
      @department = Department.find(params[:id])
    end

    def sub_params
      params.require(:department).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/departments_helper.rb
module DepartmentsHelper
end

app/views/departments/edit.html.erb
<h1>Departments#edit</h1>
<p>Find me in app/views/departments/edit.html.erb</p>

app/views/departments/index.html.erb
<h1>Departments#index</h1>


<h1>Click a Department To View Content</h1>
<%= link_to 'Create a new department', new_department_path %>
<ul>
  <% @departments.each do |departments| %>
    <li><%= link_to department.name, department %></li>
  <% end %>
</ul>



<p>Find me in app/views/departments/index.html.erb</p>

app/views/departments/new.html.erb
<h1>Departments#new</h1>
<p>Find me in app/views/departments/new.html.erb</p>



<h1>New Department</h1>
<%= form_for @department do |f| %>
  <%= f.label :name %>

<% end %>

app/views/departments/show.html.erb
<h1>Departments#show</h1>

<h1><%= @department.name %></h1>
<hr />



<p>What would you like to do?</p>
<br />
<%= link_to 'Edit Department', edit_department_path(@department) %>
<br />
<%= link_to 'Delete Department', @department, method: :delete %>



<%= link_to 'Back', pages_path %>

app/views/departments/skip-routes.html.erb
<h1>Departments#skip-routes</h1>
<p>Find me in app/views/departments/skip-routes.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DepartmentStoreApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>